### ISSUE TITLE
React context does not propagate to components props

### ISSUE THREAD

**Issue by Zaid-Ajaj** [ProductiveRage/Bridge.React#17]
The [context](https://facebook.github.io/react/docs/context.html) feature of React does not work with the way the props are defined in C# react components. I read the code and understood how (and why) the props are being wrapped during initialization and unwrapped when someone wants to access them. 

I have been experiementing with [ReactRouter](https://github.com/ReactTraining/react-router) and it seems that when I map a route to a component, the context properties in ReactRouter do not propagate into `this.props` because `this.props` actually returns the wrapped `value` in `this.props.value`. But even when I debug `this.props` (not `this.props.value`) it still seems to be empty. 

I found a (very hacky) workaround by using `Func<TProps, ReactElement>`  as a component (where TProps is some type that `props` has). Only then the context is propagated to `props` but this is a stateless component and I would like to use a statefull component

I guessed that a solution would be to merge the "original" props with the wrapped props value but I am not able to find a point during app execution where the "original" props exist. 

Any suggestions?

**Comment by ProductiveRage** [comment]
Let me see what I can find out. So that I can get my head around what you're trying to do, where are you setting context? Or where would you like to set context if you could?

This quote from the article you linked makes me a little bit wary:

> If you want your application to be stable, don't use context. It is an experimental API and it is likely to break in future releases of React.

But it would be nice if it could be supported for those cases where it can be worthwhile.

What would be really helpful would be if you could include a small code sample of how you would like the code to work, so that I can see where it could be helpful to set context and then read it again? Or is that going to be a bit difficult because it's the ReactRouter library that you're trying that is doing the context setting / reading magic?

**Comment by Zaid-Ajaj** [comment]
Excuse me, my head was spinning when I wrote the issue after trying to look for
> Let me see what I can find out. So that I can get my head around what you're trying to do, where are you setting context? Or where would you like to set context if you could?

If possible, I actually don't want to play around with context. 

Let me simplify the issue and showcase my scenario, in this introductory [article](https://github.com/ReactTraining/react-router/blob/master/docs/guides/RouteConfiguration.md) it is shown the following example:
```js
const Message = React.createClass({
  render() {
    return <h3>Message {this.props.params.id}</h3>
  }
})

render((
  <Router>
    <Route path="/" component={App}>
      <Route path="about" component={About} />
      <Route path="inbox" component={Inbox}>
        <Route path="messages/:id" component={Message} />
      </Route>
    </Route>
  </Router>
), document.body)
```
As you can see, there exists a `params` property on the props in the `Message` component. I seem to have no access to such properties when I access `this.props` from a `Component` (in C#). These extra properties on  `props` are due to some magic that `ReactRouter` is doing. I am not sure if it's using the same `context` feature I talked about but that is the closest thing I could find. Maybe it's called a `Provider`, something like the one `react-redux` uses to propagate the store or the one `muiThemeProvider` from `material-ui` that is used to propagate the theme to all child components. these (let us for now call them) `Providers` seem to inject extra properties on the `props` and these are lost when the props are wrapped in our C# component. 
I managed to get react-router to work with Bridge.React like this:
```csharp
React.Render 
(
    ReactRouter.Router
    (
        ReactRouter.BrowserHistory(),
        ReactRouter.NestedRoute(new RouteProps { Path = "/", Component = MakeLayout("Apps created with Bridge.React") },
            ReactRouter.Index(Html.H1("Select an App from the list above")),
            ReactRouter.Route("todo-app", new TodoApp("C# Canonical Todo App"))
        )
    ),
    Document.GetElementById("main")
);
```
The `TodoApp` component used with the `todo-app` route is a statefull component. The props in there know nothing about `params` nor any other ReactRouter specific properties.


Hopefully I made the issue somewhat clearer,
Any ideas? 

Thanks a lot for your time!!

**Comment by Zaid-Ajaj** [comment]
Code for [ReactRouter.zip](https://github.com/ProductiveRage/Bridge.React/files/755826/ReactRouter.zip) (not a full project, only a couple of source files with sub-namespace Bridge.React.Router)

It will not work right out of the box for the master branch of this repo. I made way too many changes to my local repo such that merging it would break many stuff in master, for now I think you only need to remove the `sealed` modifier from `Attributes` to make `LinkProps` able to inherit from it.

**Comment by ProductiveRage** [comment]
Ok.. I've got _some_ good news, which is always nice, but I don't think that it's likely to be the end of this issue! :)

From what I can tell of the ReactRouter, it doesn't directly expose anywhere that context is being used. Which is what is recommended by the React documentation - that the magic happens under the hood so that, as a library author, only your code has to change if React's context implementation changes in the future; meaning that people who use your library do _not_ have to change their code because they did _not_ have to interact with context directly.

That's part of the good news because the other part is that I have a small but complete example where context is written and read by non-Bridge components and where this context flows correctly even when Bridge components are introduced in between.. below are three components; the ThemeProvider, the CSharpWrapper and the Child. The ThemeProvider and Child are JavaScript components (with Bridge.NET bindings) and the CSharpWrapper is a Bridge.React StatelessComponent. The ThemeProvider sets up some context to pass down the tree, which the Child will need to read. The ThemeProvider is the top level component, it has a CSharpWrapper child and that has a Child child. The context data is successfully passed through the CSharpWrapper and is available to Child.

Although I need to remind myself properly how the ReactRouter works, I _think_ that there are parallels - the ThemeProvider in the example here is like the Router and the Child component is like the Link. They are both components provided by external JavaScript. The CSharpWrapper is like the components that are rendered for each route.

```
using Bridge;
using Bridge.Html5;
using Bridge.React;

namespace Issue17Repro
{
	public static class StartUp
	{
		[Ready]
		private static void Go()
		{
			// Inspired by code from http://javascript.tutorialhorizon.com/2015/06/06/using-context-and-childcontext-in-react/
			/*@
				window.ThemeProvider = React.createClass({
					displayName: "ThemeProvider",
					childContextTypes: {
						color: React.PropTypes.string.isRequired
					},
					getChildContext: function getChildContext() {
						return { color: "red" };
					},
					render: function render() {
						return this.props.children;
					}
				});

				window.Child = React.createClass({
					displayName: "Child",
					contextTypes: {
						color: React.PropTypes.string.isRequired
					},
					render: function render() {
						return React.createElement(
							"div",
							null,
							"Color: ",
							this.context.color
						);
					}
				});
			 */

			var innerChild = new Child(); // This is JS a component that reads context
			var wrapper = new CSharpWrapper(innerChild); // This is a C# component that doesn't read or write context (but won't interfere with it either)
			var themeProvider = new ThemeProvider(wrapper); // This is a JS component that writes context

			React.Render(
				themeProvider,
				Document.GetElementById("main")
			);
		}

		/// <summary>
		/// This is a C# binding to the JavaScript ThemeProvider component (that sets up context for child components to use)
		/// </summary>
		[External]
		[Name("ThemeProvider")]
		[IgnoreCast]
		public sealed class ThemeProvider
		{
			[Template("React.createElement(ThemeProvider, null, {children})")]
			public ThemeProvider(params Union<ReactElement, string>[] children) { }

			[External] public extern static implicit operator ReactElement(ThemeProvider component);
			[External] public extern static implicit operator Union<ReactElement, string>(ThemeProvider component);
		}

		/// <summary>
		/// This is a C# binding to the JavaScript Child component (that requires that context be configured by an ancestor)
		/// </summary>
		[External]
		[Name("Child")]
		[IgnoreCast]
		public sealed class Child
		{
			[Template("React.createElement(Child, null)")]
			public Child() { }

			[External] public extern static implicit operator ReactElement(Child component);
			[External] public extern static implicit operator Union<ReactElement, string>(Child component);
		}

		/// <summary>
		/// This is just a C# component that can sit in between the ThemeProvider and the Child JavaScript component to prove that having
		/// wrapper components like this between the components further up the chain (that set context values) and those further down the
		/// chain (that read context values) doesn't mess anything up
		/// </summary>
		public sealed class CSharpWrapper : StatelessComponent<string>
		{
			public CSharpWrapper(params Union<ReactElement, string>[] children) : base(null, children) { }

			public override ReactElement Render()
			{
				return DOM.Div(new Attributes { ClassName = "wrapper" }, Children);
			}
		}
	}
}
```

So, hopefully, this means that it's _possible_ to do what you want to with the ReactRouter.

What I'm a bit concerned about, though, is that clearly there must be something going wrong somewhere - otherwise you wouldn't have raised the issue! There's a _chance_ that it's to do with the ReactRouter bindings that you're writing.. I think that my next step would be to try to go from the minimal example above and try to work with the ReactRouter project itself.

I've got a lot on this week, so I'm not sure how quickly I'll be able to make progress on this, but that doesn't mean that I'm ignoring it!

**Comment by ProductiveRage** [comment]
If you want to try out my code then create a new project called "Issue17Repro", add the Bridge.React NuGet package, add a bridge.json file to the project root:

```
{
  "output": "Bridge/output",
  "combineScripts": true
}
```
and then add the following "Test.html" file to the project root:

```
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>Bridge Bridge.React.Examples</title>
</head>
<body>
    <div id="main">Loading..</div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.4.2/react.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.4.2/react-dom.js"></script>
    <script src="Bridge/output/Issue17Repro.js"></script>
</body>
</html>
```

I know that you've probably done this a hundred times by now, I just thought that I'd try to make it a bit easier for you if you want to experiment with what I wrote about at all! :)

**Comment by Zaid-Ajaj** [comment]
Wow thanks alot for the sample, so it seems that external js would be needed after all. I will dive deeper into this soon when time permits. I will keep you updated :)

**Comment by ProductiveRage** [comment]
Are you happy for me to close this issue for now? If you find any problems with this then you can always re-open it.
