### ISSUE TITLE
new List<ReactComponent>() fails at runtime

### ISSUE THREAD

**Issue by DanTup** [ProductiveRage/Bridge.React#2]
If you understand what `ReactComponent` is, you'll know why this doesn't work; but as someone new trying to work with the library, it doesn't seem unreasonable to try this:

```
var children = new List<ReactComponent>();
foreach (/* ... */
{
    children.Add(/* ...*/);
}
```

However it'll fail at runtime because Bridge doesn't know what ReactComponent is.

Since it's probably not going to be possible to make code like this work, it would be great to generate a compile error (using an Analyzer).

**Comment by ProductiveRage** [comment]
That's a good idea. Makes a lot of sense. I need to try to wrap my head around what will and won't work.

Functions with return values that have an "extern" type (such as ReactElement) as a return value should be fine since these are essentially remove entirely from the generated JavaScript. Similarly, I think that it should be fine to have a variable declared as being an IEnumerable<ReactElement> - eg.

`IEnumerable<ReactElement> children = nulll;`

should be fine.

Things that won't be fine are where Bridge generates JavaScript that tries to reference the type. So

`var children = new List<ReactElement>();`

fails because Bridge tries to generate an instance of a class in JavaScript that depends upon the "ReactElement" type, which doesn't exist.

I haven't tested yet but presume that the following will fail for the same reason-

`var element = default(ReactElement);`

I haven't tested this either yet, but I presume that it will fail if you try to call a generic method where one of the generic type parameters is an extern type - eg.

`var x = Something.Get<ReactElement>();`

**Comment by ProductiveRage** [comment]
The latest NuGet package (Bridge.React 1.6.3) includes an analyser for the originally reported issue, any instantiation of a type that has a type parameter that references ReactElement will be identified as an error.

This includes

```
var x = new List<ReactElement>();
var y = new Dictionary<string, ReactElement>();
var z = new List<KeyValuePair<string, ReactElement>>();
```

If a class has the [IgnoreGeneric] attribute then its type parameters will not be checked since they will not appear in the generated JavaScript.

The other failure cases that I mentioned are not covered yet (calling generic methods and specifying a ReactElement and default(ReactElement)) but may be in a future release.

After upgrading the NuGet package in a solution, you will likely have to restart Visual Studio for it to load the analyser (if so, there should be a warning in the Error List about it).

![Example error](https://cloud.githubusercontent.com/assets/742348/16176480/380d2ef6-3609-11e6-9657-800f98dc17e9.png)
