### ISSUE TITLE
[question] Bridge.React vs React Native

### ISSUE THREAD

**Issue by qqgg231** [ProductiveRage/Bridge.React#38]
I am new to Javascript / React.

I would like to write React Native web/desktop/mobile apps using c#. 
This approach would allow me to:
-share most code
-use c# language, which I love. 
-have native ui on web/android/ios/macos/linux/windows

Is it possible to do that with Bridge.React?

**Comment by ProductiveRage** [comment]
I'm afraid that the Bridge.React bindings are _only_ bindings for the web aspect of React and there is nothing relating to React Native.

I haven't tried React Native at all yet and so I don't know how simple or complex that it would be to add support for it. Even if it was quite straightforward, I would probably suggest that it be a separate repo / NuGet package because I would imagine that you would be unlikely to have one C# project that builds both the web frontend and the mobile applications.

You are the second person to ask about this, so I'll try to update the README soon to explain this for anyone else wondering in the future!

**Comment by desarrollo03TR** [comment]
Why not Xamarin? it support iOS, Android, Mac and Windows.

**Comment by ProductiveRage** [comment]
@desarrollo03TR - I guess that if someone really wanted to share code between web applications _and_ desktop applications _and_ mobile applications then they could use Xamarin for the mobile apps and to share some common C# libraries between the different application (though I suspect that there would be little-to-no sharing of UI code between mobile, desktop and web applications).

For writing a desktop application, there are now Bridge bindings to Electron (via [retyped](https://retyped.com/))
that one might consider. The Slack client, for example, is (I believe, according to [this](https://slack.engineering/building-hybrid-applications-with-electron-dc67686de5fb)) written in this manner. A lot of people complain about the resources that Electron applications use, though..
