### ISSUE TITLE
Update to Bridge 17.x and React new

### ISSUE THREAD

**Issue by colderlord** [ProductiveRage/Bridge.React#40]
Hello
Will you update bridge depencies to 17.x ?
Will you update support React 16.3.x ?
Regards.

**Comment by ProductiveRage** [comment]
I need to see what's broken with 17.1, whether recompiling with the latest version of Bridge will fix the problem and whether the nuget package will then still work with older versions of Bridge or if it will require 17 or later (the Bridge Team quite often make breaking changes that prevent code built in one version of the compiler from working with others).

In terms of React 16.3, I thought that it did work OK - are you getting errors with it even if you use an older version of Bridge that does work with the current Bridge.React package?

**Comment by colderlord** [comment]
We update our project to bridge 17.1, then we got some problems with Bridge.React.
We just update Bridge.React manually with some fixes: change `toArray` -> `ToArray`, thats all. Works fine, but Bridge.React wont work on previous versions Bridge... So... maybe need some directives or just update to new version :)

**Comment by ProductiveRage** [comment]
I've looked into this and it shouldn't be a huge problem. It seems like code compiled with Bridge 16 won't work with code that is compiled with Bridge 17 and vice versa (this isn't particularly unusual with Bridge major version releases but I do wish that they would make more of an effort towards compatibility on this front). It just means for me that I need to update the Bridge dependency in all of my NuGet packages (such as [Immutable](https://github.com/ProductiveRage/Bridge.Immutable), [Immutable.Collections](https://github.com/ProductiveRage/Bridge.Immutable.Collections), [ReactRouting](https://github.com/ProductiveRage/Bridge.ReactRouting), etc..) at the same time and probably given them a major version bump to indicate that they will be pulling in a Bridge dependency that will likely make the code not compatible with older versions.

Hopefully I will be able to do this over the weekend.

On the plus side, using the latest version of the React library itself (the JS library) should not require any changes and should work right now. To test this out, I changed the script tags in the demo.html and Tests.html files in the projects Bridge.React.Examples and Bridge.React.Tests within the Bridge.React repo and everything seemed to work fine (see this commit: [2acb3c56fefbb1d0eebebb6b8042c4539a2da4ba](https://github.com/ProductiveRage/Bridge.React/commit/2acb3c56fefbb1d0eebebb6b8042c4539a2da4ba).

**Comment by ProductiveRage** [comment]
I've released a new version of Bridge.React to nuget.org (4.0.0) that supports Bridge 17.1 (in fact, 17.1 is the minimum version for the package).

I've also started working upgrading some of my other packages but it sounds like they don't apply to you, so they shouldn't hold you up!

While we're talking about React version, are you aware my "Bridge.ReactLoader" NuGet package? It lets you pull in the React library JS via a NuGet package rather than having to include it yourself as a JS file in your project or by specifying additional script tags in your markup. If you use the "[combineScripts](https://github.com/bridgedotnet/Bridge/wiki/global-configuration#combinescripts)" option that the bridge.json files support then it will even include the React JS into the final combined output of your project, so that you end up with one single .js file. Just thought it might be useful for you! The project is on GitHub [here](https://github.com/ProductiveRage/Bridge.ReactLoader) and through NuGet (I pushed version 16.4.1 earlier, which is the first release of the package that includes the JS for React 16.4).
