### ISSUE TITLE
Unable to add disabled or hidden attributes to option element

### ISSUE THREAD

**Issue by dnaustin** [ProductiveRage/Bridge.React#44]
I would like to add an option element  to a select group that is disabled and hidden to act as a placeholder as the select element does not allow placeholders directly. There are currently no available attributes in OptionAttributes to set these.

**Comment by ProductiveRage** [comment]
I think that you are quite right about the "[Disabled](https://www.w3schools.com/tags/att_option_disabled.asp)" attribute being missed from the OptionAttributes class*

However.. I'm not sure sure about it being hidden. How would you do that now in vanilla JS React (or even JS and the DOM)? Hidden with styling or hidden as a special state?

* (It's possible that I didn't include the "Disabled" attribute because it wasn't available in React a few years ago - eg. see https://github.com/JedWatson/react-select/issues/145 - but it seems like it should be safe to add it now)

**Comment by ProductiveRage** [comment]
I've published a new version of Bridge.React (4.2.0) that includes the Disabled attribute on OptionAttributes (and checked that it works properly with React first!) - it's being indexed by nuget.org now and so should be available for you to upgrade to soon.

**Comment by dnaustin** [comment]
I have tested it out and it works perfectly - thank you! I have worked around the "hidden" attribute by setting the option to `display: none` and setting the default value of the select to the placeholder option.
