### ISSUE TITLE
Stateless component with life cycle events?

### ISSUE THREAD

**Issue by kendallb** [ProductiveRage/Bridge.React#51]
I have a component I am trying to port to React, that is entirely stateless but it needs to hook into the lifecycle events (specifically ComponentDidMount) as it hooks into the real DOM to connect up some keyboard and focus events. Basically it makes enter on tagged input elements move to the next one in tab sequence, not submit the form and and also select the entire text element value when you focus on it. I have built it at the moment using the normal Component class, but I have to pass it a bogus state class that has nothing in it as it actually has no state. The StatelessComponent and PureComponent classes do not have any hooks for the lifecycle events.

Is it possible to expose the lifecycle events to the StatelessComponent class?

**Comment by ProductiveRage** [comment]
The StatelessComponent does not support these methods because it essentially wraps a pure render function for React and these do not support life cycle methods.

The PureComponent _does_ support life cycle methods, including ComponentDidMount.

**Comment by ProductiveRage** [comment]
I think that using IAmImmutable is the easiest way with Bridge and C# to create components, particularly PureComponent classes. However, if you were writing pure components in JavaScript then it's still a good practice to use immutable props classes since the React library wants to treat props (and state) as immmutable - many people use the immutable.js library, which also would mean that a "shallow equality check" is safe to perform.

One of the nice things about the PureComponent's ShouldComponentUpdate implementation is that if you have any bound functions on the props then it will use some knowledge of Bridge's internals to compare those bound functions and consider them equivalent if their contents are the same and their bind target is the same. This is not the case in JavaScript or TypeScript, as mentioned in the [Bind in Render](https://reactjs.org/docs/faq-functions.html#bind-in-render) and [Arrow Function in Render](https://reactjs.org/docs/faq-functions.html#bind-in-render) sections of the React docs:

> "Using Function.prototype.bind in render creates a new function each time the component renders, which may have performance implications (see below)."

**Comment by kendallb** [comment]
Yeah I am aware of the cost of arrow functions in render calls in normal JSX files. It's nice that Bridge removes that cost automatically for you.

As for the IAmImmutable support, the biggest issue that I see is that the code generated for CtorSet is quite significant, so would be adding a reasonable amount of non-trivial overhead to use it for setting the read only properties. I assume though you can mark a class as IAmImmutable but not actually need to use CtorSet at all?

**Comment by ProductiveRage** [comment]
You don't need to use IAmImmutable at all, Bridge React is completely unaware of that interface. You can write your own immutable types and update methods if you want but I don't know how you would do it and they be both strictly immutable and more succinct than the IAmImmutable types with the "With" method support.

I'm getting the impression that you're trying to evaluate these libraries without actually writing any code using them. I don't think you'll learn as much than you would be actually prototyping something.

**Comment by kendallb** [comment]
I am in the middle of writing the code to test it out, which is why I was noticing that the code generated for CtorSet is quite complex. Probably my worst habit is worrying about micro optimizing even bit of code I write, but I like to make sure it's as efficient as possible as well as as safe as possible to promote safe programming. I understand why you use the class, I just wish there was a way to do the same without as much overhead at runtime.
